const $=s=>document.querySelector(s);const screens={auth:$('#auth-screen'),menu:$('#menu-screen'),game:$('#game-screen')};
const SKINS=[['reef','Reef 🐠','hsl(188 90% 58%)'],['sunset','Sunset 🐡','hsl(22 90% 62%)'],['royal','Royal 🐟','hsl(260 80% 70%)'],['lime','Lime 🐠','hsl(92 75% 58%)'],['deep','Deep Sea 🦈','hsl(215 75% 62%)']];
const defaultSave={bestSize:1,bestEaten:0,skin:'reef',account:null};let save=JSON.parse(localStorage.getItem('fishArenaSave')||'null')||defaultSave;
function persist(){localStorage.setItem('fishArenaSave',JSON.stringify(save))}function show(s){Object.values(screens).forEach(x=>x.classList.add('hidden'));s.classList.remove('hidden')}
function renderMenu(){ $('#best-size').textContent=save.bestSize.toFixed(1);$('#best-eaten').textContent=save.bestEaten;$('#welcome').textContent=save.account?`Signed in as ${save.account}`:'Playing locally as guest';$('#skin-list').innerHTML=SKINS.map(([id,name])=>`<button class="skin ${save.skin===id?'selected':''}" data-skin="${id}">${name}</button>`).join('');document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>{save.skin=b.dataset.skin;persist();renderMenu()})}
$('#auth-form').addEventListener('submit',e=>{e.preventDefault();const email=$('#email').value.trim();if(!email)return;save.account=email;persist();$('#auth-status').textContent='Signed in locally. Add Firebase config for cloud accounts.';renderMenu();show(screens.menu)});
$('[data-action="signup"]').onclick=()=>$('#auth-form').requestSubmit();$('#guest-btn').onclick=()=>{save.account=null;persist();renderMenu();show(screens.menu)};$('#signout-btn').onclick=()=>{save.account=null;persist();renderMenu()};
$('#play-btn').onclick=()=>startGame();$('#leave-btn').onclick=()=>{stopGame();renderMenu();show(screens.menu)};
$('#host-btn').onclick=()=>{const code=Math.random().toString(36).slice(2,8).toUpperCase();$('#room-status').textContent=`Room ${code} created. Share the code with a friend.`;startGame(code)};$('#join-btn').onclick=()=>{const code=prompt('Enter room code:');if(code)startGame(code.toUpperCase())};
const canvas=$('#game'),ctx=canvas.getContext('2d');let raf=null,input={x:0,y:0},player,fish=[],particles=[],running=false,room='';
function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function spawnFish(){const r=12+Math.random()*25;fish.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r,size:.6+Math.random()*2.7,vx:(Math.random()-.5)*.7,vy:(Math.random()-.5)*.7,h:Math.floor(Math.random()*360)})}
function startGame(code=''){room=code;show(screens.game);running=true;player={x:innerWidth/2,y:innerHeight/2,r:22+save.bestSize*3,size:save.bestSize,score:0,vx:0,vy:0};fish=[];particles=[];for(let i=0;i<45;i++)spawnFish();input={x:player.x,y:player.y};$('#room-code').classList.toggle('hidden',!room);$('#room-code').textContent=room?`ROOM ${room}`:'';$('#game-tip').textContent=room?'P2P room prototype — WebRTC signaling required to connect peers.':'Move with mouse/touch. Eat smaller fish!';cancelAnimationFrame(raf);loop()}
function stopGame(){running=false;cancelAnimationFrame(raf);save.bestSize=Math.max(save.bestSize,player?.size||1);save.bestEaten=Math.max(save.bestEaten,player?.score||0);persist()}
function setInput(x,y){input.x=x;input.y=y}canvas.addEventListener('pointermove',e=>setInput(e.clientX,e.clientY));canvas.addEventListener('pointerdown',e=>setInput(e.clientX,e.clientY));
function drawFish(f,me=false){ctx.save();ctx.translate(f.x,f.y);const ang=Math.atan2(f.vy||0.001,f.vx||1);if(!me)ctx.rotate(ang);ctx.scale(f.r/22,f.r/22);ctx.fillStyle=me?SKINS.find(s=>s[0]===save.skin)[2]:`hsl(${f.h} 75% 60%)`;ctx.beginPath();ctx.ellipse(0,0,26,15,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(-20,0);ctx.lineTo(-38,-14);ctx.lineTo(-38,14);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(14,-5,4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#071827';ctx.beginPath();ctx.arc(15,-5,2,0,Math.PI*2);ctx.fill();ctx.restore()}
function loop(){if(!running)return;const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#063b52';ctx.fillRect(0,0,w,h);for(let i=0;i<35;i++){const x=(i*97+(performance.now()*.015))%w,y=(i*53)%h;ctx.fillStyle='#ffffff10';ctx.beginPath();ctx.arc(x,y,2+(i%3),0,7);ctx.fill()}
const dx=input.x-player.x,dy=input.y-player.y,dist=Math.hypot(dx,dy);if(dist>8){player.vx+=(dx/dist*0.5-player.vx)*.09;player.vy+=(dy/dist*0.5-player.vy)*.09}player.x=Math.max(player.r,Math.min(w-player.r,player.x+player.vx));player.y=Math.max(player.r,Math.min(h-player.r,player.y+player.vy));
for(const f of fish){f.x+=f.vx;f.y+=f.vy;if(f.x<-50)f.x=w+50;if(f.x>w+50)f.x=-50;if(f.y<-50)f.y=h+50;if(f.y>h+50)f.y=-50;const d=Math.hypot(f.x-player.x,f.y-player.y);if(d<player.r+f.r*.7){if(f.size<player.size){player.score++;player.size+=.025;player.r=22+player.size*3;particles.push({x:f.x,y:f.y,t:1});Object.assign(f,{x:Math.random()*w,y:Math.random()*h,r:12+Math.random()*25,size:.6+Math.random()*2.7,vx:(Math.random()-.5)*.7,vy:(Math.random()-.5)*.7,h:Math.random()*360})}else if(player.size>1.2){player.size*=.92;player.r=22+player.size*3}}drawFish(f)}drawFish(player,true);particles=particles.filter(p=>p.t>0);for(const p of particles){p.t-=.03;ctx.fillStyle=`rgba(120,230,255,${p.t})`;ctx.beginPath();ctx.arc(p.x,p.y,30*(1-p.t),0,7);ctx.fill()}$('#size-label').textContent=player.size.toFixed(1);$('#score-label').textContent=player.score;raf=requestAnimationFrame(loop)}
renderMenu();show(screens.auth);

// WebRTC transport foundation. A tiny signaling service can be connected later; GitHub Pages itself cannot act as a signaling server.
export class PeerRoom{constructor(){this.pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});this.channel=this.pc.createDataChannel('fish-arena');this.channel.onopen=()=>console.log('P2P connected');this.channel.onmessage=e=>console.log('peer',e.data)}send(state){if(this.channel.readyState==='open')this.channel.send(JSON.stringify(state))}}
