const $=s=>document.querySelector(s);const screens={auth:$('#auth-screen'),menu:$('#menu-screen'),game:$('#game-screen')};
const SKINS=[['reef','Reef 🐠','hsl(188 90% 58%)'],['sunset','Sunset 🐡','hsl(22 90% 62%)'],['royal','Royal 🐟','hsl(260 80% 70%)'],['lime','Lime 🐠','hsl(92 75% 58%)'],['deep','Deep Sea 🦈','hsl(215 75% 62%)']];
const EVOS=[['FRY',1],['MINNOW',2.5],['CLIPPER',5],['HUNTER',9],['TITAN',15]];const defaultSave={bestSize:1,bestEaten:0,skin:'reef',account:null};let save=JSON.parse(localStorage.getItem('fishArenaSave')||'null')||defaultSave;function persist(){localStorage.setItem('fishArenaSave',JSON.stringify(save))}function show(s){Object.values(screens).forEach(x=>x.classList.add('hidden'));s.classList.remove('hidden')}
function evoFor(size){let e=EVOS[0];for(const x of EVOS)if(size>=x[1])e=x;return e}function renderMenu(){$('#best-size').textContent=save.bestSize.toFixed(1);$('#best-eaten').textContent=save.bestEaten;$('#welcome').textContent=save.account?`Signed in as ${save.account}`:'Playing locally as guest';$('#skin-list').innerHTML=SKINS.map(([id,name])=>`<button class="skin ${save.skin===id?'selected':''}" data-skin="${id}">${name}</button>`).join('');document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>{save.skin=b.dataset.skin;persist();renderMenu()})}
$('#auth-form').addEventListener('submit',e=>{e.preventDefault();save.account=$('#email').value.trim();persist();renderMenu();show(screens.menu)});$('#signup-btn').onclick=()=>$('#auth-form').requestSubmit();$('#guest-btn').onclick=()=>{save.account=null;persist();renderMenu();show(screens.menu)};$('#signout-btn').onclick=()=>{save.account=null;persist();show(screens.auth)};$('#play-btn').onclick=()=>startGame();$('#leave-btn').onclick=()=>{stopGame();renderMenu();show(screens.menu)};$('#host-btn').onclick=()=>{const code=Math.random().toString(36).slice(2,8).toUpperCase();$('#room-status').textContent=`Room ${code} created`;startGame(code)};$('#join-btn').onclick=()=>{const code=prompt('Room code');if(code)startGame(code.toUpperCase())};
const canvas=$('#game'),ctx=canvas.getContext('2d');let raf=null,input={x:0,y:0},player,fish=[],particles=[],running=false,room='',boosting=false,lastEvo='FRY';function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function spawnFish(){const r=12+Math.random()*25;fish.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r,size:.6+Math.random()*2.7,vx:(Math.random()-.5)*.7,vy:(Math.random()-.5)*.7,h:Math.floor(Math.random()*360)})}
function startGame(code=''){room=code;show(screens.game);running=true;player={x:innerWidth/2,y:innerHeight/2,r:22+save.bestSize*3,size:save.bestSize,score:0,vx:0,vy:0};fish=[];particles=[];for(let i=0;i<45;i++)spawnFish();input={x:player.x,y:player.y};lastEvo=evoFor(player.size)[0];$('#evo-label b').textContent=lastEvo;$('#room-code').classList.toggle('hidden',!room);$('#room-code').textContent=room?`ROOM ${room}`:'';cancelAnimationFrame(raf);loop()}
function stopGame(){running=false;cancelAnimationFrame(raf);save.bestSize=Math.max(save.bestSize,player?.size||1);save.bestEaten=Math.max(save.bestEaten,player?.score||0);persist()}function setInput(x,y){input.x=x;input.y=y}canvas.addEventListener('pointermove',e=>setInput(e.clientX,e.clientY));canvas.addEventListener('pointerdown',e=>setInput(e.clientX,e.clientY));
const joy=$('#joystick'),stick=$('#stick');function joyMove(e){const r=joy.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=e.clientX-cx,dy=e.clientY-cy,d=Math.hypot(dx,dy),max=36;if(d>max){dx=dx/d*max;dy=dy/d*max}stick.style.transform=`translate(${dx}px,${dy}px)`;input.x=player.x+dx*10;input.y=player.y+dy*10}function joyEnd(){stick.style.transform='';input.x=player.x;input.y=player.y}joy.addEventListener('pointerdown',e=>{joy.setPointerCapture(e.pointerId);joyMove(e)});joy.addEventListener('pointermove',e=>{if(e.buttons)joyMove(e)});joy.addEventListener('pointerup',joyEnd);joy.addEventListener('pointercancel',joyEnd);$('#boost-btn').addEventListener('pointerdown',()=>boosting=true);['pointerup','pointercancel','pointerleave'].forEach(e=>$('#boost-btn').addEventListener(e,()=>boosting=false));
function drawFish(f,me=false){ctx.save();ctx.translate(f.x,f.y);const ang=Math.atan2(f.vy||.001,f.vx||1);if(!me)ctx.rotate(ang);ctx.scale(f.r/22,f.r/22);ctx.fillStyle=me?SKINS.find(s=>s[0]===save.skin)[2]:`hsl(${f.h} 75% 60%)`;ctx.beginPath();ctx.ellipse(0,0,26,15,0,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-20,0);ctx.lineTo(-38,-14);ctx.lineTo(-38,14);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(14,-5,4,0,7);ctx.fill();ctx.fillStyle='#071827';ctx.beginPath();ctx.arc(15,-5,2,0,7);ctx.fill();ctx.restore()}
function loop(){if(!running)return;const w=innerWidth,h=innerHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle='#063b52';ctx.fillRect(0,0,w,h);const dx=input.x-player.x,dy=input.y-player.y,dist=Math.hypot(dx,dy);let speed=boosting?1.05:.5;if(dist>8){player.vx+=(dx/dist*speed-player.vx)*.1;player.vy+=(dy/dist*speed-player.vy)*.1}player.x=Math.max(player.r,Math.min(w-player.r,player.x+player.vx));player.y=Math.max(player.r,Math.min(h-player.r,player.y+player.vy));
for(const f of fish){f.x+=f.vx;f.y+=f.vy;if(f.x<-50)f.x=w+50;if(f.x>w+50)f.x=-50;if(f.y<-50)f.y=h+50;if(f.y>h+50)f.y=-50;const d=Math.hypot(f.x-player.x,f.y-player.y);if(d<player.r+f.r*.7){if(f.size<player.size){player.score++;player.size+=.025;player.r=22+player.size*3;particles.push({x:f.x,y:f.y,t:1});const now=evoFor(player.size)[0];if(now!==lastEvo){lastEvo=now;$('#evo-label b').textContent=now;$('#evo-name').textContent=now;$('#evolution').classList.remove('hidden');setTimeout(()=>$('#evolution').classList.add('hidden'),1300)}}else if(player.size>1.2){player.size*=.92;player.r=22+player.size*3}}drawFish(f)}drawFish(player,true);particles=particles.filter(p=>p.t>0);$('#size-label').textContent=player.size.toFixed(1);$('#score-label').textContent=player.score;raf=requestAnimationFrame(loop)}renderMenu();show(screens.auth);
export class PeerRoom{constructor(){this.pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});this.channel=this.pc.createDataChannel('fish-arena')}send(state){if(this.channel.readyState==='open')this.channel.send(JSON.stringify(state))}}
