services:
  - type: web
    name: remote-browser
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: VNC_PASSWORD
        sync: false
      - key: RESOLUTION
        value: 1280x800x24
      - key: APP_PORT
        value: 10000
